# Generated by Django 5.2.1 on 2025-05-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
