# Generated by Django 5.2.1 on 2025-05-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_survey', '0002_question_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserResponse',
        ),
    ]
