# Generated by Django 5.2.1 on 2025-05-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customuser_avatar_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
