# Generated by Django 5.2.1 on 2025-05-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0002_userpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='activated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
