# Generated by Django 5.2.1 on 2025-05-25 05:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_pricingplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpackage',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='userpackage',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 5, 45, 32, 782210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='activated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
