# Generated by Django 5.2.1 on 2025-05-25 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0005_userpackage_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 8, 48, 55, 869546, tzinfo=datetime.timezone.utc)),
        ),
    ]
